[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
via_ir = true
optimizer = true
optimizer_runs = 2000


[lint]
level = "off"
unsafe_typecast = "allow"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
